apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "temporary-contents.fullname" . }}
  labels:
    app: {{ template "temporary-contents.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "temporary-contents.name" . }}
        release: {{ .Release.Name }}
        {{- range $key, $val := .Values.podLabels }}
        {{- if tpl ($val) $}}
        {{ tpl ($key) $ }}: {{ tpl ($val) $ | quote }}
        {{- end }}
        {{- end}}
    spec:
      containers:
        - name: {{ template "temporary-contents.name" . }}
          image: {{ template "temporary-contents.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
          env:
            - name: TERMINATION_GRACE_PERIOD_SECONDS
              value: {{ .Values.terminationGracePeriodSeconds | quote }}
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  {{ if .Values.mongodb.uriSecretName -}}
                  name: {{ .Values.mongodb.uriSecretName }}
                  {{ else -}}
                  name: {{ .Release.Name }}-mongoconfig
                  {{ end -}}
                  key: mongodb-uri
            - name: LOG_LEVEL
              value: {{ default "info" .Values.logLevel | quote }}
            {{- if .Values.featureFlagsURI }}
            - name: FEATURE_FLAGS_URI
              value: {{ tpl ( .Values.featureFlagsURI ) . | quote }}
            {{- end }}
            {{- if .Values.auth.enabled }}
            - name: AUTH_ENABLED
              value: {{ .Values.auth.enabled | quote }}
            - name: AUTH_JWKS_URI
              value: {{ tpl ( .Values.auth.jwksURI ) . | quote }}
            - name: AUTH_JWT_AUD
              value: {{ .Values.auth.jwtAud | quote }}
            - name: AUTH_JWT_ISS
              value: {{ .Values.auth.jwtIss | quote }}
            {{- end }}
            {{- if .Values.tokenAuth.enabled }}
            - name: TOKEN_AUTH_ENABLED
              value: {{ .Values.tokenAuth.enabled | quote }}
            - name: TOKEN_AUTH_PRIVATE_KEY
              value: {{ .Values.tokenAuth.privateKey | quote }}
            - name: TOKEN_AUTH_KID
              value: {{ .Values.tokenAuth.kid | quote }}
            - name: TOKEN_AUTH_URL
              value: {{ tpl ( .Values.tokenAuth.url ) . | quote }}
            {{- end }}
            {{- if .Values.encryption.enabled }}
            - name: ENCRYPTION_CLIENT
              value: "encryption"
            - name: ENCRYPTION_URI
              value: {{ tpl ( .Values.encryption.url ) . | quote }}
            {{- end }}
            - name: ACCESS_CONTROL_ENABLED
              value: {{ default false .Values.accessControl.enabled | quote }}
            - name: PDS_URI
              value: {{ tpl ( .Values.accessControl.url ) . | quote }}
            - name: STORAGE_PATH
              value: "/qlik/temp-contents"
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.port }}
          volumeMounts:
            - mountPath: /qlik/temp-contents
              name: temp-files
              readOnly: false
{{- if .Values.global }}{{- if .Values.global.certs }}{{- if .Values.global.certs.enabled }}
{{- include "qlik.ca-certificates.volumeMount" . | nindent 12 }}
{{- end }}{{- end }}{{- end }}
      volumes:
        - name: temp-files
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "temporary-contents.fullname" .) }}
      {{- else }}
          emptyDir: {}
      {{- end -}}
{{- if .Values.global }}{{- if .Values.global.certs }}{{- if .Values.global.certs.enabled }}
{{- include "qlik.ca-certificates.volume" . | nindent 8 }}
{{- end }}{{- end }}{{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
  selector:
    matchLabels:
      app: {{ template "temporary-contents.name" . }}
      release: {{ .Release.Name }}
